"""Add growth_trackers table

Revision ID: 70901fe7a42f
Revises: ffdc0a98111c
Create Date: 2024-11-19 14:31:39.770770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70901fe7a42f'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growth_trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=255), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('date_logged', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('growth_trackers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_growth_trackers_user_id'), ['user_id'], unique=False)

    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journals_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journals_user_id'))

    op.drop_table('journals')
    with op.batch_alter_table('growth_trackers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_growth_trackers_user_id'))

    op.drop_table('growth_trackers')
    # ### end Alembic commands ###
